name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  job1:
    name: Check Dockerfile
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Get specific changed files
        id: changed
        uses: tj-actions/changed-files@v9
        with:
          files: Dockerfile
  job2:
    name: Build image
    needs: job1
    runs-on: ubuntu-latest
    if: needs.job1.outputs.any_changed
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zhuoqiw/ros-pcl:1.10.0
